### ISSUE TITLE
Create Faculty Log-in Page

### ISSUE THREAD

**Issue by HappyPetDog** [violessi/CourseMinder#14]
### Preliminaries:
- None

### To-do:
- [ ]  Set up the required form fields
  - [ ] Email
  - [ ] Password
- [ ] Implement working log-in button
  - [ ] ONLY redirects the user to the Dashboard page upon successful authentication
  - [ ] Display error messages and prevent redirection in case of errors
