### ISSUE TITLE
Create Faculty Sign-up Page

### ISSUE THREAD

**Issue by HappyPetDog** [violessi/CourseMinder#15]
### Preliminaries:
- None

### To-do:
- [ ] Set up the required form fields
  - [ ] Degree program
  - [ ] Name
  - [ ] Student Number
  - [ ] Password
  - [ ] Password Confirmation
- [ ] Implement **working** buttons
  - [ ] Sign-in button: Redirects the user to the dashboard page
  - [ ] Log-in button: Redirects the user to the log-in page
