### ISSUE TITLE
Setup Database via Firebase

### ISSUE THREAD

**Issue by HappyPetDog** [violessi/CourseMinder#17]
### To-do:
- [ ] Create table for student and faculty
  - [ ] For each student, create the following fields:
    - [ ] Degree Program
    - [ ] Full Name
    - [ ] Student Number
    - [ ] Password
    - [ ] List of Courses
  - [ ] For each faculty, create the following fields:
    - [ ] Degree Program
    - [ ] Full Name
    - [ ] Email
    - [ ] Password
- [ ] Create courses table containing the following fields:
  - [ ] Course Code 
  - [ ] Course Name
  - [ ] Course Description
  - [ ] Number of Units
