### ISSUE TITLE
Create Curriculum Graph Page

### ISSUE THREAD

**Issue by HappyPetDog** [violessi/CourseMinder#18]
### Preliminaries:
- [ ] #17

### To-do:
- [ ] For each of the courses in Computer Science:
  - [ ] Create a page containing Course Name, Code, Description, and No. of Units
  - [ ] Create a button that redirects to the course data page
