### ISSUE TITLE
Create Add New Semester Feature

### ISSUE THREAD

**Issue by HappyPetDog** [violessi/CourseMinder#19]
### To-do:
- [ ] Create button to add new semester
- [ ] Display Total Number of Units, Total GWA, and Current Latin Honor Standing
- [ ] Create a pop-up container that asks for the semester (1st, 2nd, or Midyear) and the current academic year

### Reference:

![Image](https://github.com/violessi/CourseMinder/assets/77038513/42faec6c-268d-4769-94e3-6ba74ffe946a)

![Image](https://github.com/violessi/CourseMinder/assets/77038513/e61a567a-d33b-44f0-8e88-e2fe2b6c37f2)

![Image](https://github.com/violessi/CourseMinder/assets/77038513/34c87115-1557-4235-a4d9-4ab3381c70e7)
