### ISSUE TITLE
Create Add New Class and Class Grade Feature

### ISSUE THREAD

**Issue by HappyPetDog** [violessi/CourseMinder#20]
### Preliminaries:
- #17

### To-do:
- [ ] Create Add New Class Button
- [ ] Create pop-up box asking for Course Name, No. of Units, and Grade
- [ ] Displays total number of units, GWA, and honorable scholarship for that semester
- [ ] Displays semester and academic year

### Note:
- Must automatically update the total number of units, GWA, and honorable scholarship in the add new class page
- Must also update the number of units and GWA in the corresponding box in the add semester page
- The total number of units, total GWA, and Latin Honor Standing must also be automatically updated after every class added

### Reference:

![Image](https://github.com/violessi/CourseMinder/assets/77038513/76a41277-5934-4702-8242-fcffb739938a)

![Image](https://github.com/violessi/CourseMinder/assets/77038513/31bcfa40-1b33-4900-bcd3-d44bbc65fae9)

![Image](https://github.com/violessi/CourseMinder/assets/77038513/358e6d57-ff50-49eb-925b-681deaf3f912)
