### ISSUE TITLE
Create Sign-up Page

### ISSUE THREAD

**Issue by violessi** [violessi/CourseMinder#7]
## Sign-up Page
The Sign-up Page allows new users to register for an account on the platform.

### To-do:
- [ ] Set up the required form fields
  - [ ] Degree program
  - [ ] Name
  - [ ] Student Number
  - [ ] Password
  - [ ] Password Confirmation
- [ ] Implement **working** buttons
  - [ ] Sign-in button: Redirects the user to the dashboard page
  - [ ] Log-in button: Redirects the user to the log-in page

### Notes:
- For this sprint, only expected values for each required field will be considered, without actual user creation. 
- No input validation needed (e.g. invalid student number).
- Can use this [package](https://tabler.io/icons) for icons.
- Maintain consistency in the website theme 

### Reference:
<p align="center">
  <img src="https://github.com/violessi/CourseMinder/assets/108144748/0cbca536-3349-49f0-bf72-5f14e386ecdd" width="50%"  />
</p>
