### ISSUE TITLE
Create Log-in Page

### ISSUE THREAD

**Issue by violessi** [violessi/CourseMinder#8]
## Log-in Page
The Log-in Page enables existing users to securely access their accounts by entering their credentials.

### To-do:
- [ ] Set up the required form fields
  - [ ] Student number 
  - [ ] Password
- [ ] Implement **working** log-in button
  - [ ] ONLY redirects the user to the Dashboard page upon successful authentication
  - [ ] Display error messages and prevent redirection in case of errors

### Notes:
- For this sprint, only expected values for each required field will be considered, without actual user authentication and validation.
- Can use this [package](https://tabler.io/icons) for icons.
- Maintain consistency in the website theme 

### Reference:
<p align="center">
  <img src="https://github.com/violessi/CourseMinder/assets/108144748/299d3be5-373e-4814-bc53-2cb2063d9155" width="50%"  />
</p>
